### ISSUE TITLE
Error turning "choice" exercise into "code" exercise

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mumuki-laboratory#1107]
Despite of changing the type of exercise, the options remains.

**Comment by rodri042** [comment]
@Gustrucco y cómo hay que hacer?

repro fallida: https://www.youtube.com/watch?v=xlB-ayWRmfQ

Parece similar a https://github.com/mumuki/mumuki-bibliotheca/issues/145

**Comment by Gustrucco** [comment]
Hola Rodri. El tema es el siguiente. Si bien en la biblioteca figura correctamente, a la hora de enviar la solución del ejercicio, no valida los tests del lenguaje en cuestión. Sino que lo evalúa como si fuese multiple choice y por ende rompe. Te hago un video?

**Comment by rodri042** [comment]
Si podés, joya!

On Sep 14, 2018 6:10 PM, "Gustavo Trucco" <notifications@github.com> wrote:

Hola Rodri. El tema es el siguiente. Si bien en la biblioteca figura
correctamente, a la hora de enviar la solución del ejercicio, no valida los
tests del lenguaje en cuestión. Sino que lo evalúa como si fuese multiple
choice y por ende rompe. Te hago un video?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mumuki/mumuki-laboratory/issues/1107#issuecomment-421485243>,
or mute the thread

**Comment by Gustrucco** [comment]
No pude replicarlo. Quizás esté solucionado. El problema era que si el ejercicio había sido un multiple choice o single choice, y pasaba a ser uno de código, no importaba si la solución estuviese bien o mal, daba rojo igual diciendo  "La respuesta no es correcta".

En resumen, en bibliotheca aparecía bien, pero lo evaluaba como si fuese un multiple choice siempre.

**Comment by Gustrucco** [comment]
Exactamente eso. Si ves el json mantiene las opciones del choice, a pesar de que bibliotheca registre el ejercicio correctamente.

**Comment by rodri042** [comment]
Franco dice: `Quizás lo que pasa es que publica algunos campos que quiere borrar como nil, y la api al recibirlos al estar en nil los deja como está en lugar de borrarlos` - Relacionado con mumuki-platform#321
