### ISSUE TITLE
Scratch Integration

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1197]

**Comment by luchotc** [comment]
I've worked on a simplified version of scratch 3.0 which i've deployed here: https://luchotc.github.io/scratch-gui/, so we could use this link to embed it on Mumuki.
Also, I've managed to use it directly by including two .js files and modifying them a little bit (as there's no main html file, it was being included directly as a child of the body element).
Until this point, i think it's cleaner to just embed the iframe as it has no limitations whatsoever regarding of usability. If we need to persist or evaluate ourself  the submissions, we'll need to use the second approach.

**Comment by luchotc** [comment]
- [ ] Be able to generate a Mulang AST from scratch-blocks. 
- [ ] Add support in Mulang for checking whether a structure is used a certain number of times or not. Quoting the specific suggestion: "It would be nice to check if a certain block type is used X number of times, like if a conditional is used 3 times in the solution" 
- [ ] Add the possibility for the teacher to provide an example solution  
- [ ] Start working in the concept of projects inside Mumuki. What are the main differences with a regular exercise?
- [ ] Add support for using custom sprites and backdrops
- [ ] Add support for easily sharing a solution. A suggestion was to download the source code, but in the case of blocks it isn't readable, so we should decide if we want to use the existing support from Scratch or implement something ourselves.
- [ ] Allow a student to solve exercises along with other students. A simplified implementation of this could be just to add the option for an user to include other students in an specific exercise or project so that the submission counts for all of them.
- [ ] Improve the current review method for an exercise. Allow for a teacher, other students or the students themselves to do it.
- [ ] Improve the teacher interface for seeing the students results. Take into account that the teacher could be quite agnostic about programming concepts.

**Comment by flbulgarelli** [comment]
Done in https://github.com/mumuki/mumuki-scratch-runner
