### ISSUE TITLE
Allow users to know usage stats from their profile

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1540]
Currently there is no way for a user to know very basic things like: 

* How many exercises has they solved - assignment with `top_submission_status`  in green state. This is motivated by https://github.com/mumuki/mumuki-laboratory/issues/1541. 
* Which percentage of book's exercises has they solved 
* How many message has they sent, and how many of them were validated
* ~How many threads has they opened~

All those stats should be displayed in a per-organization basis, and may be displayed in the user's profile. 

Those stats are important for users which otherwise can't have a real metric of their progress, and for moderators, which otherwise can't weight their efforts.

This information should be displayed in absolute terms, at least. However it would be really nice if you could also display for the current monthly period, or even selecting the period unit. 

Also, this information should be displayed numerically, but having a graphical display - like a punchard o histogram - would be nice. I am open to suggestions here @LauraMangifesta @rgonzalezt @fedescarpa    @felipecalvo 

This may be related to https://github.com/mumuki/mumuki-laboratory/issues/1527

**Comment by felipecalvo** [comment]
Quick reminder that there's a (relatively new) object called `UserStats` which pairs an user with an organization and could be useful for storing denormalized fields if we choose to do so.

**Comment by felipecalvo** [comment]
Alright, so here's what we decided:

We'll be calling this `Activity`. It'll be a profile tab such as `Profile` itself, `Messages` and `Discussions`. This activity tab should have a week filter, as well as an option to see the aggregated total. We're thinking of limiting the options to the last 12 weeks, as around 3 months is enough for most projects.

The four stats we'll be showing are:
  * Number of exercises solved
  * How many messages sent in forum
  * How many validated messages sent in forum
  * % of total exercises solved in this organization's book.

This fourth stat should only be shown on the total view, as it doesn't make as much sense on a week-to-week basis.

All stats should correspond only to the current organization. That is, # of exercises solved in the current organization, % of total on current book, etc.

Besides adding this tab, we decided to switch the profile to a vertical view, with all tabs on the left. The following mockups by @rgonzalezt assume this new layout. However, this new Activity tab can still be done with the current layout. Maybe you could do the user stats first and then we can change the layout at a later point, so no conflicts arise.

This is what the Activity tab would look like. The stats are divided in two parts: exercises and forum (espacio de consultas). I'm not so sure about how the divider looks but we can see how it turns out.

![image](https://user-images.githubusercontent.com/11304439/105091306-6746bb80-5a7e-11eb-8cee-6bf7d28c9d92.png)

The tabs on the right filter by week, akin to GitHub's year selector on the profile.

![image](https://user-images.githubusercontent.com/11304439/105091778-1e433700-5a7f-11eb-8fc7-a86986f7b01f.png)

I guess it makes most sense to consider each Monday as a new week, i.e. `Semana del 18/01`, `Semana del 11/01`, etc. in descending (from newest to oldest) order. The topmost tab should show the `Total` (or `All-time`) statistics. That will be the default tab.

When a week is selected, the `% of exercises in book` doesn't show:

![image](https://user-images.githubusercontent.com/11304439/105091954-5e0a1e80-5a7f-11eb-8bee-d67e0fa52ee0.png)

**Comment by faloi** [comment]
Hi @rgonzalezt and @felipecalvo, please review this first mockup. Data is obviously faked, but the markup is real:

![image](https://user-images.githubusercontent.com/1585835/106518948-543ddd80-64b9-11eb-8c09-0374556dee88.png)

**Comment by felipecalvo** [comment]
This is great! :heart: I don't have anything to say, really. I'd like to see how this looks on mobile - maybe the week selector should go to the bottom or something.

**Comment by faloi** [comment]
> This is great! :heart: I don't have anything to say, really. I'd like to see how this looks on mobile - maybe the week selector should go to the bottom or something.
> 

Yep, right now that's the behavior: the indicators go full width and the week selector goes to the bottom.

**Comment by faloi** [comment]
@felipecalvo here is a GIF of mobile view (same problem with the header yet):

![mumuki](https://user-images.githubusercontent.com/1585835/106643279-3f6c5300-6568-11eb-9018-b3f8f8ca72ad.gif)

**Comment by felipecalvo** [comment]
Awesome! :+1: I think the header alignment you mentioned should be the only thing missing.
