### ISSUE TITLE
Conditional hints

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#358]
Many times when writing an exercise, the teacher already knows a set of common errors that her students could commit. The thing is that you **do want** them to commit the error **before** a hint is displayed, and right now the platform doesn't have any kind of support for that.

What I'm suggesting is _conditional_ hints, that would be displayed **if and only if** a set of rules are fulfilled. Those rules could be against a particular test, an expectation, a specific pattern or any combination of those.

**Comment by flbulgarelli** [comment]
Renaming `adaptive hints` -> `conditional hints`, since we will reserve the adaptive term for things that depend on the way the student followed the path. 

I also propose to rename and merge `conditional hints` term with `progressive tips` introduced in #961 and #952 into just `tips`. 

That way, we will have the following model: 

* hints are always static and context-free. They are explanations and hints about how to solve the exercise. They are provided by bibliotheca and are specific to the exercise.
* feedback is a set of explanations based on the student's solution, that are aimed to humanized the compiler and test tools errors.  They are provided by the runners, and are general to any exercise. 
* tips are dynamic feedback based on the student's solution, but specific  specific to each exercise. They are a set of rules provided by bibliotheca, but evaluated by laboratory, based on the runner response. 

The rules of the `tips` will be specified using the following language: https://github.com/mumuki/mumuki-platform/issues/318
