### ISSUE TITLE
Do something about the need help link

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-laboratory#560]
Students DO NOT USE the _"Need some help?"_ link.

@aguspina suggested to automatically highlight it when the student fails a few times (3? 4?).

**Comment by flbulgarelli** [comment]
Perhaps the problem is that the label is wrong: "necesitas ayuda" sounds like we are going to call a human, or that we are going to send an email. Another problem is that is stated like a question. 

We are actually offering a hint. Perhaps changing the label could do the trick: "¡Quiero una pista!", "¡Dame una pista!" o simply "Pistas".

**Comment by flbulgarelli** [comment]
And we could use this icon: http://fontawesome.io/icon/lightbulb-o/

**Comment by flbulgarelli** [comment]
And little less margin.

**Comment by flbulgarelli** [comment]
![screencapture-central-localmumuki-io-3000-exercises-24-programacion-funcional-alternativas-guardas-y-patrones-tipando-tuplas-1476798367984](https://cloud.githubusercontent.com/assets/677436/19480275/23bcc8b4-9520-11e6-87a3-8ea3113a62e9.png)

**Comment by flbulgarelli** [comment]
@faloi

**Comment by flbulgarelli** [comment]
Reopening, @estafaniamiguel

**Comment by flbulgarelli** [comment]
However, 11 months ago this issue has dropped interest in the teachers community, and there is no clear way of solving it. Closing
