### ISSUE TITLE
Console seems to take editor into account

### ISSUE THREAD

**Issue by geh** [mumuki/mumuki-laboratory#636]
Console seems to take editor into account, but it is not obvious from the beginning.

So "compilation" errors thrown by the console are sometimes errors of bad code left in the editor.

Moreover, even when the editor is clean, it seems that the console keeps on throwing parse errors when evaluating an obviouly correct expression.

**Comment by flbulgarelli** [comment]
Hi!

> Console seems to take editor into account, but it is not obvious from the beginning.
> So "compilation" errors thrown by the console are sometimes errors of bad code left in the editor.

Yes, that is true and by design. We have considered to have a "ignore-editor" switch in the console, but after explaning how it works, it looks to be good enough. 

We understand, however, that we could make it more obvious. Do you have any suggestions about how to achieve it?

> Moreover, even when the editor is clean, it seems that the console keeps on throwing parse errors when evaluating an obviouly correct expression.

That may be a bug! In which exercise is occurring? Could you show us the errors, please?

**Comment by flbulgarelli** [comment]
@estefaniamiguel pointed out the same today. It is not intuitive that the editor code is loaded in the console. Moreover, it is annoying that the console gets unusable when the editor has errors. 

Perhaps we could add a switch - a checkbox -  that lets the user load or not the console into the editor.
