### ISSUE TITLE
Multiple editors support

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#711]
It would be nice to support multiple code editors tabs. 

They should be customizable by the student.

**Comment by julian-berbel** [comment]
We discussed three possible approaches to this problem:

1. Sending a mashup string of all files divided by a special separator

2. Handling multiple files as a Hash of hashes such as
```
{
  'foo': {
    format: 'rb'
    content: '...'
  }
  'bar': {
    format: 'rb'
    content: '...'
  }
}
```
While keeping backwards compatibility so that if a string is received, follow the already existing flow, otherwise run a new flow

3. Reifying files and sending an array of such objects
We've decided on this alternative for being the most politically correct and the fact that none of the alternatives are trivial to implement either way
