### ISSUE TITLE
Missing trash icon in blockly canvas

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#974]
Otherwise we can't delete blocks

**Comment by luchotc** [comment]
@aguspina @fedescarpa I've been struggling with this one for a while now. Blockly trashcan only accepts to be repositioned programatically by setting a distance from the bottom. The horizontal position is not configurable.
 I've managed to position it horizontally by applying a transform on resize. The problem is that Blockly repositions the trash in other scenarios like onClick on the toolbox and i can't subscribe to that event
